application: new-project-template
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /admin/.*
  script: admin.py
  login: admin
  
- url: .*
  script: main.py
